### ISSUE TITLE
Access control to the database?

### ISSUE THREAD

**Issue by ahellander** [ajallow07/Cloud-Metric#4]
Should there be some notion of application client key in order to register and monitor a node/app? What stops me from registering more nodes to someone's cluster?

**Comment by ajallow07** [comment]
The initial design was to allow addition of several nodes in the cluster with no restriction on the number of nodes to be added. That would could be part of the next release.

**Comment by ahellander** [comment]
If you might work on it in the future, you should not close the issue, just mark if as "enhancement". Only close an issue when it is decided that it is eiter not valid or won't ever be fixed.
